ALTER TABLE `ProviderTool` MODIFY `pricingMetric` ENUM('REQUEST','INPUT_SECOND','OUTPUT_SECOND','INPUT_BYTE') NOT NULL;
ALTER TABLE `ProviderToolPriceVersion` MODIFY `pricingMetric` ENUM('REQUEST','INPUT_SECOND','OUTPUT_SECOND','INPUT_BYTE') NOT NULL, ADD COLUMN `proportional` BOOLEAN NOT NULL DEFAULT false, ADD COLUMN `resolutionRates` JSON NULL;
