CREATE TABLE `ProviderTool` (
  `id` VARCHAR(191) NOT NULL,
  `provider` ENUM('BYTEPLUS','NVIDIA','GROQ','GEMINI','CLOUDFLARE') NOT NULL,
  `providerToolId` VARCHAR(191) NOT NULL,
  `displayName` VARCHAR(191) NOT NULL,
  `description` TEXT NOT NULL,
  `category` VARCHAR(32) NOT NULL,
  `executionMode` ENUM('ASYNC','SYNC') NOT NULL,
  `pricingMetric` ENUM('REQUEST','INPUT_SECOND','OUTPUT_SECOND') NOT NULL,
  `capabilities` JSON NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ProviderTool_provider_providerToolId_key`(`provider`, `providerToolId`),
  INDEX `ProviderTool_enabled_category_idx`(`enabled`, `category`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ProviderToolPriceVersion` (
  `id` VARCHAR(191) NOT NULL,
  `providerToolId` VARCHAR(191) NOT NULL,
  `publicationKey` VARCHAR(36) NULL,
  `publicationHash` VARCHAR(64) NULL,
  `providerCostMicroUsd` BIGINT NOT NULL,
  `customerCredits` BIGINT NOT NULL,
  `fxBaisaNumerator` BIGINT NOT NULL,
  `fxBaisaDenominator` BIGINT NOT NULL,
  `targetMarginBps` INTEGER NOT NULL,
  `pricingMetric` ENUM('REQUEST','INPUT_SECOND','OUTPUT_SECOND') NOT NULL,
  `unitQuantity` INTEGER NOT NULL DEFAULT 1,
  `creditsPerBaisa` BIGINT NOT NULL DEFAULT 1,
  `providerCostBasisNote` VARCHAR(255) NULL,
  `effectiveFrom` DATETIME(3) NOT NULL,
  `effectiveTo` DATETIME(3) NULL,
  `createdById` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ProviderToolPriceVersion_publicationKey_key`(`publicationKey`),
  INDEX `ProviderToolPriceVersion_providerToolId_effectiveFrom_idx`(`providerToolId`, `effectiveFrom`),
  INDEX `ProviderToolPriceVersion_effectiveFrom_effectiveTo_idx`(`effectiveFrom`, `effectiveTo`),
  CONSTRAINT `ProviderToolPriceVersion_providerToolId_fkey` FOREIGN KEY (`providerToolId`) REFERENCES `ProviderTool`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ProviderToolPriceVersion_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ProviderToolExecution` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `createdById` VARCHAR(191) NOT NULL,
  `providerToolId` VARCHAR(191) NOT NULL,
  `priceVersionId` VARCHAR(191) NOT NULL,
  `status` ENUM('QUEUED','SUBMITTING','PROCESSING','SUCCEEDED','FAILED','CANCELLED','MANUAL_REVIEW') NOT NULL DEFAULT 'QUEUED',
  `idempotencyKey` VARCHAR(64) NOT NULL,
  `requestHash` VARCHAR(64) NOT NULL,
  `requestPayload` JSON NOT NULL,
  `resultPayload` JSON NULL,
  `providerTaskId` VARCHAR(191) NULL,
  `providerRequestId` VARCHAR(191) NULL,
  `quotedQuantity` INTEGER NOT NULL,
  `actualQuantity` INTEGER NULL,
  `reservedCredits` BIGINT NOT NULL DEFAULT 0,
  `chargedCredits` BIGINT NOT NULL DEFAULT 0,
  `actualProviderCostMicroUsd` BIGINT NULL,
  `retryCount` INTEGER NOT NULL DEFAULT 0,
  `maxAttempts` INTEGER NOT NULL DEFAULT 8,
  `nextAttemptAt` DATETIME(3) NULL,
  `errorCode` VARCHAR(128) NULL,
  `errorMessage` TEXT NULL,
  `submittedAt` DATETIME(3) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ProviderToolExecution_idempotencyKey_key`(`idempotencyKey`),
  UNIQUE INDEX `ProviderToolExecution_providerToolId_providerTaskId_key`(`providerToolId`, `providerTaskId`),
  INDEX `ProviderToolExecution_status_nextAttemptAt_updatedAt_idx`(`status`, `nextAttemptAt`, `updatedAt`),
  INDEX `ProviderToolExecution_organizationId_createdAt_idx`(`organizationId`, `createdAt`),
  INDEX `ProviderToolExecution_createdById_createdAt_idx`(`createdById`, `createdAt`),
  CONSTRAINT `ProviderToolExecution_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ProviderToolExecution_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ProviderToolExecution_providerToolId_fkey` FOREIGN KEY (`providerToolId`) REFERENCES `ProviderTool`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ProviderToolExecution_priceVersionId_fkey` FOREIGN KEY (`priceVersionId`) REFERENCES `ProviderToolPriceVersion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
