CREATE TABLE `MailMessage` (
  `id` VARCHAR(191) NOT NULL,
  `kind` ENUM('SECURITY','ROUTINE') NOT NULL,
  `priority` ENUM('HIGH','NORMAL') NOT NULL DEFAULT 'NORMAL',
  `status` ENUM('PENDING','QUEUED','SENDING','RETRY','SENT','FAILED','SUPPRESSED') NOT NULL DEFAULT 'PENDING',
  `template` VARCHAR(191) NOT NULL,
  `recipient` VARCHAR(191) NOT NULL,
  `subject` VARCHAR(191) NOT NULL,
  `textBody` LONGTEXT NOT NULL,
  `htmlBody` LONGTEXT NOT NULL,
  `sensitive` BOOLEAN NOT NULL DEFAULT false,
  `userId` VARCHAR(191) NULL,
  `organizationId` VARCHAR(191) NULL,
  `idempotencyKey` VARCHAR(191) NOT NULL,
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `nextAttemptAt` DATETIME(3) NULL,
  `providerMessageId` VARCHAR(191) NULL,
  `lastErrorCode` VARCHAR(191) NULL,
  `lastErrorMessage` TEXT NULL,
  `queuedAt` DATETIME(3) NULL,
  `sendingAt` DATETIME(3) NULL,
  `sentAt` DATETIME(3) NULL,
  `failedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `MailMessage_idempotencyKey_key`(`idempotencyKey`),
  INDEX `MailMessage_status_priority_createdAt_idx`(`status`, `priority`, `createdAt`),
  INDEX `MailMessage_status_nextAttemptAt_idx`(`status`, `nextAttemptAt`),
  INDEX `MailMessage_userId_createdAt_idx`(`userId`, `createdAt`),
  INDEX `MailMessage_organizationId_createdAt_idx`(`organizationId`, `createdAt`),
  INDEX `MailMessage_recipient_createdAt_idx`(`recipient`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
